FROM  osixia/phpldapadmin

# docker run -p 6443:443 --env PHPLDAPADMIN_LDAP_HOSTS=adldsorclprod.ar.bsch  --detach ldap:latest
#  --env PHPLDAPADMIN_HTTPS=false
# https://hub.docker.com/r/osixia/phpldapadmin