FROM  gitlab.ar.bsch:4567/santander-tecnologia/docker-base-images/other/websphere:v8.5

ENV http_proxy "http://proxy.ar.bsch:8080"
ENV https_proxy "http://proxy.ar.bsch:8080"
ENV no_proxy ".ar.bsch"
e

xKLtgj1zz91wMf43x2q3